# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20170730_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
