# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to='/'),
        ),
    ]
