# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170416_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to='blog/'),
        ),
    ]
